# Generated by Django 4.0.5 on 2022-06-26 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=100)),
                ('task_description', models.TextField()),
                ('deadline', models.DateTimeField(default=datetime.datetime(2022, 6, 26, 22, 21, 47, 601717))),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
